### ISSUE TITLE
Labeling of impedance is incorrect in 'View Transducer" dialog

### ISSUE THREAD

**Issue by jcrademacher** [signalkinetics/linkbudget#1]
Using tag v1.0.2 / Windows 11, the CSV that is loaded into the dialog is not necessarily in R/X impedance format (could also be G/B or polar format), but the label in the dialog is always R/X. The impedance plot to the right is correct though as the internal app.tr.Z variable is already converted appropriately upon loading of the transducer. 

![image](https://github.com/signalkinetics/linkbudget/assets/13385111/410deadd-7360-40a0-ae7e-be72f1a01ebc)

Proposed fix: in TransducerDialog.mlapp, line 29 could be changed to reflect the contents of the app.tr.Z variable.

**Comment by allam-a** [comment]
Thanks for catching. Fixed in 1.0.3.
